name: food_delivery_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  collection: ^1.19.1
  flutter_credit_card: ^4.1.0
  intl: ^0.20.2
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  firebase_core_web: ^2.12.0
  firebase_auth_web: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
assets:
  - assets/images/burgers/
  - assets/images/salads/
  - assets/images/drinks/
  - assets/images/desserts/

